makeMalloc: malloc-example.c
	gcc -o malloc-example malloc-example.c


messwithMemory: mess-with-memory.c
	gcc -o mess-with-memory mess-with-memory.c


make6-2: 6-2.c
	gcc -o 6-2 6-2.c

makePointing: who_you_pointing_at.c
	gcc -o who_you_pointing_at who_you_pointing_at.c
