makeAll: 2-1.c 2-2.c 2-4.c 2-6.c 2-7.c 2-9.c 2-11.c assign-elements-of-an-array.c
	gcc -o 2-1 2-1.c
	gcc -o 2-2 2-2.c
	gcc -o 2-4 2-4.c
	gcc -o 2.6 2-6.c
	gcc -o 2-7 2-7.c
	gcc -o 2-9 2-9.c
	gcc -o 2-11 2-11.c
	gcc -o assign-elements-of-an-array assign-elements-of-an-array.c

clean : 
	rm 2-1 2-2 2-4 2-6 2-7 2-9 2-11 assign-elements-of-an-array
