makeAll: using-limits-header.c sizeof-operator.c integer_conversion_rank.c
	gcc -o using-limits-header using-limits-header.c
	gcc -o integer-conversion-rank integer_conversion_rank.c
	gcc -o sizeof-operator sizeof-operator.c


clean: 
	rm using-limits-header
