makeAll: switch.c
	gcc -o switch switch.c	
	gcc -o random_enum_examples random_enum_examples.c 
	gcc -o memset_example memset_example.c
	gcc -o do_while do_while.c	 
	gcc -o jump-statements jump-statements.c



clean:
	rm switch
